[package]
name = "payjoin_ffi"
version = "0.13.0"
license = "MIT OR Apache-2.0"
edition = "2021"
exclude = ["tests"]

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "payjoin_ffi"

[build-dependencies]
uniffi = { version = "0.26.1", features = ["build"] }

[dev-dependencies]
uniffi = { version = "0.26.1", features = ["bindgen-tests"] }
bdk = { version = "0.29.0", features = ["all-keys", "use-esplora-ureq", "keys-bip39"] }
bitcoind = { version = "0.34.1", features = ["0_21_2"] }
log = "0.4.18"
[dependencies]
#https://github.com/payjoin/rust-payjoin/commit/e7037b23b0f29beda39f5e161d3d7924d2060dd4
payjoin = { git= "https://github.com/payjoin/rust-payjoin", rev = "e7037b23b0f29beda39f5e161d3d7924d2060dd4",  features = ["send", "receive", "base64", "v2"] }
uniffi = { version = "0.26.1" }
thiserror = "1.0.47"
ohttp = { version = "0.5.1" }


[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[profile.release-smaller]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
strip = true


[features]
default = ["uniffi/cli"]
