[package]
name = "pdk-ffi"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "pdk_ffi"

[build-dependencies]
uniffi = { version = "0.24.3", features = ["build"] }

[dev-dependencies]
uniffi = { version = "0.24.3", features = ["bindgen-tests"] }
assert_matches = "1.5.0"
env_logger = "0.10.0"
bitcoind = { version = "0.32.0", features = ["0_21_2"] }


[dependencies]
anyhow = "1.0.70"
env_logger = "0.10.0"
log = "0.4.7"
serde = { version = "1.0.160", features = ["derive"] }
payjoin = { version = "0.9.0", features = ["send", "receive", "rand"] }
serde_json = "1.0.103"
uniffi = { version = "0.24.3" }
hex = "0.4.3"
url = "2.4.0"
thiserror = "1.0.47"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[profile.release-smaller]
inherits = "release"
opt-level = 'z'    
lto = true         
codegen-units = 1  
panic = 'abort'     
strip = true  

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"


[features]
default = ["uniffi/cli"]
